---
- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - pyenv

- name: Install and set default Python
  ansible.builtin.shell: |
    "pyenv install {{ python_version }}"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.pyenv/versions/{{ python_version }}"
