---
- name: Install Oh My ZSH
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh

- name: Create a default ZSH configuration
  ansible.builtin.template:
    src: templates/.zshrc.j2
    dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
    owner: "{{ lookup('env', 'USER') }}"
    force: yes
  
- name: Install homebrew packages
  community.general.homebrew:
    name: [
      "ag",
      "bat",
      "fzf",
      "gh",
      "k9s",
      "jq",
      "tmux"
    ]
    state: latest
    update_homebrew: yes

- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items: 
    - firefox
    - iterm2
    - visual-studio-code

- name: Ensure tmux directory exists
  ansible.builtin.file:
    path: /Users/{{ lookup("env", "USER") }}/.tmux
    state: directory

- name: Configure tmux
  ansible.builtin.template:
    src: templates/.tmux.j2
    dest: /Users/{{ lookup("env", "USER") }}/.tmux/.tmux.conf
    owner: "{{ lookup('env', 'USER') }}"
    force: yes
